variables:
    DETTRACE_NO_CPUID_INTERCEPTION: 1

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    lsb_release -a
    uname -a
    stat /dev/null
  displayName: 'Debugging information'

- script: |
    make docker
  displayName: 'Build the Docker image'

- script: |
    make test-docker
  displayName: 'Run the tests'
